### ISSUE TITLE
The included example is not compiling

### ISSUE THREAD

**Issue by specing** [mosteo/ada4cmake#1]
```
example $ mkdir build
$ cd build/
$ cmake ..
-- The C compiler identification is GNU 6.4.0
-- The CXX compiler identification is GNU 6.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /data/users/specing/programs/ada4cmake/example/build

$ make
Scanning dependencies of target main_ada
[ 10%] Building C object CMakeFiles/main_ada.dir/main.c.o
make[2]: *** No rule to make target 'libadatest.a', needed by 'main_ada'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/main_ada.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

PS: Why is it limited to out-of-tree builds only?

**Comment by mosteo** [comment]
I just tested it in ubuntu 18.04 LTS and it worked for me. What's your platform?

The reason for out-of-build is that GPR project files do not allow the library dir and source dir to be the same. It can be worked around, e.g., by having your Ada sources in a subfolder.

**Comment by specing** [comment]
Gentoo with system compiler replaced with one from https://github.com/sarnold/ada-overlay.git (as Gentoo has no working Ada toolchain of its own).

Generated makefile: https://paste.pound-python.org/show/UB4TrUWvEn153dE0D1wI

**Comment by mosteo** [comment]
I'm afraid I don't have expertise on Gentoo, nor any system ready to try. If you know of a docker image where the problem can be reproduced that would be helpful.

**Comment by specing** [comment]
Can you please upload a working Makefile? Perhaps I can figure out what went wrong while generating it.

**Comment by mosteo** [comment]
Here's the entire build folder generated in my machine.
[build.zip](https://github.com/mosteo/ada4cmake/files/2183762/build.zip)

**Comment by specing** [comment]
Well, swapping CMakeFiles/Makefile2 lines 62 to 98  for lines 99 to 135 makes my version of CMakeFiles/Makefile2 identical to yours and makes the build work. Swapping them back produces my problem.

How to make cmake generate them in the correct order?

**Comment by mosteo** [comment]
I'm sorry but I don't know about CMake generated internals so I feel unable to help you there.

**Comment by specing** [comment]
According to ngladitz on IRC, the problem here is that target_link_libraries does not expect the file to be generated. They said that "cmake .. && make ada_main" should reproduce it 100% and suggested
"add_dependencies(main_ada AdaTest)" before target_link_libraries call as a workaround. This makes the build reproducibly work for me.

**Comment by mosteo** [comment]
That's curious because there's a rule for that in CMakeAda.cmake that should make that unnecesary, although it's true that your reproducer works, so the rule has to be wrong. Thanks for the catch.

**Comment by mosteo** [comment]
I have reworked the library function a bit, it should work now as intended.
