### ISSUE TITLE
Final linking

### ISSUE THREAD

**Issue by specing** [mosteo/ada4cmake#3]
How to tell cmake which additional libraries must be linked into the final executable? GPR should know this, but final linking is not done by GPR.

Testcase:

```
diff --git a/example/lib_test.adb b/example/lib_test.adb
index 4c08962..ffc8cdb 100644
--- a/example/lib_test.adb
+++ b/example/lib_test.adb
@@ -14,4 +14,10 @@ package body Lib_Test is
       null;
    end;
 
+   function Add(a,b : Interfaces.C.Int) return Interfaces.C.Int is
+      use all type Interfaces.C.Int;
+   begin
+      return a + b;
+   end;
+
 end Lib_Test;
diff --git a/example/lib_test.ads b/example/lib_test.ads
index a3426b0..f1ae0bf 100644
--- a/example/lib_test.ads
+++ b/example/lib_test.ads
@@ -7,4 +7,6 @@ package Lib_Test is
    function Give return Interfaces.C.Int;
    pragma Export(C, Give);
 
+   function Add(a,b : Interfaces.C.Int) return Interfaces.C.Int
+     with Export, Convention => C, External_Name => "ada_add";
 end Lib_Test;
diff --git a/example/main.c b/example/main.c
index 403eb45..5248336 100644
--- a/example/main.c
+++ b/example/main.c
@@ -1,10 +1,12 @@
 #include <stdio.h>
 
 int give();
+int ada_add(int, int);
 
 int main() {
 
     printf("Ada gave me %d\n", give());
+    printf("3+2 = %d\n", ada_add(3,2));
 
     return 0;
 }
```

EDIT: output is:
```
-- Configuring done                                                                                   
-- Generating done                                                               
-- Build files have been written to: /tmp/ada4cmakebuild
[ 25%] Building library ada_lib...                               
Compile                                                                          
   [Ada]          lib_test.adb
Build Libraries                                                  
   [gprlib]       ada_lib.lexch                           
   [archive]      libada_lib.a
   [index]        libada_lib.a                  
[ 25%] Built target ada_lib_build                
[ 50%] Linking C executable c_main_using_ada_lib             
lib/libada_lib.a(lib_test.o): In function `ada_add':  
lib_test.adb:(.text+0xef): undefined reference to `__gnat_rcheck_CE_Overflow_Check'
collect2: error: ld returned 1 exit status               
make[2]: *** [CMakeFiles/c_main_using_ada_lib.dir/build.make:96: c_main_using_ada_lib] Error 1
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/c_main_using_ada_lib.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

`obj/bin_test.bexch` includes a [RESULTING OPTIONS] section that includes
```
-L/tmp/ada4cmakebuild/obj/
-L/tmp/ada4cmakebuild/obj/
-L/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/adalib/
-L/usr/lib64/gcc/x86_64-pc-linux-gnu/6.4.0/adalib/
-static
-static-libgcc
/usr/lib64/gcc/x86_64-pc-linux-gnu/6.4.0/adalib/libgnat.a
```
libgnat is a very likely location of that missing symbol. Problem is that there are no .bexch files generated in the project I'd like to use this in and there has to be a better/easier way than parsing this file.

**Comment by mosteo** [comment]
Right you are. The gnat library should be added to the link of the C target.

Check now after commit 583aad259e02619be2964188ec1960ddf02ca926 which fix this in my machine. I also replaced the example with yours for the future.

**Comment by specing** [comment]
There is a deeper problem here, as illustrated by 
```
Scanning dependencies of target c_main_using_ada_lib
[ 50%] Building C object CMakeFiles/c_main_using_ada_lib.dir/main.c.o
[ 75%] Linking C executable c_main_using_ada_lib
/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lgnat
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/c_main_using_ada_lib.dir/build.make:96: c_main_using_ada_lib] Error 1
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/c_main_using_ada_lib.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

```

Namely, manually specifying libraries to link against bypasses/ignores GPRBbuild's dependency resolution and in this case does not work at all (missing -L?). But specifying -L for this case is not a solution as one's Ada library could have a dependency tree with dozens of packages. As stated in the README, replicating GPRBuild's functionality would be a huge and pointless task.

I am now investigating standalone libraries, as per @pmderodat's advice (exporting this information from GPRBuild is not possible yet): https://docs.adacore.com/gprbuild-docs/html/gprbuild_ug/gnat_project_manager.html#stand-alone-library-projects

**Comment by mosteo** [comment]
Well, at least for libgnat, being a system library (if using the system gnat), it should be locatable just as libc and libc++ are. Are you linking with gnat's gcc? 

Let me know your findings about SALs if there is anything that applies. I think it's more related to elaboration but I have never used them yet so I may be wrong.

Dynamic libraries retain their dependencies as shown by ldd. Perhaps that can help somehow.

In the end, just as you tell external libraries to gprbuild (before via switches, now via externally built projects), you must tell to CMake if it is performing the final linking. I guess. But again, I'm not an expert on linking. Actually is the part that most headaches has always given me during mixed programming.

**Comment by specing** [comment]
A very new GPRBuild (from their repository) exports a .GPR.linker_options section in the resulting static archive file. For this example the contents of it are:
```
Contents of section .GPR.linker_options:
 0000 2d4c2f74 6d702f61 64613463 6d616b65  -L/tmp/ada4cmake
 0010 632f6f62 6a2f0a2d 4c2f686f 6d652f73  c/obj/.-L/home/s
 0020 70656369 6e672f6f 70742f47 4e41542f  pecing/opt/GNAT/
 0030 32303138 2f6c6962 2f676363 2f783836  2018/lib/gcc/x86
 0040 5f36342d 70632d6c 696e7578 2d676e75  _64-pc-linux-gnu
 0050 2f372e33 2e312f61 64616c69 622f0a2d  /7.3.1/adalib/.-
 0060 6c676e61 740a2d6c 646c0a             lgnat.-ldl.
```

Using this relies on bleeding edge tools, but it seems to be the only other option to having GNAT tools do the final linking. I will try it in the following days.

I would also like to see if there is a nice way of having GNAT tools do the the final linking, but I am a newbie when it comes to cmake, so that will have to wait. Either for someone else or for a possibly long time.
